pro prog1
  ;Lectura de la imagen
    ans4a ='C:\Users\1046986683\Documents\Imagenes\Clase1\Fig1.07(b).jpg'

    READ_JPEG,ans4a,image
    tamanio=Size(image)
    print,tamanio,'tamanio de la imagen'
    nx=tamanio(1)  & ny=tamanio(2)

    Window,1,Xpos=0,Ypos=0,Xsize=nx,Ysize=ny,Title='Imagen Original'
    Tvscl,image

For j = 0,nx-1 Do Begin
 For k = 0,ny-1 Do Begin
      If (SQRT((j-nx/2)^2+(k-ny/2)^2) lt 70) Then Begin
        image(j,k)=0.5*image(j,k)
      EndIf
 EndFor
EndFor

Window,4,Xpos=nx,Ypos=0,Xsize=nx,Ysize=ny,Title='Imagen modificada'
Tvscl,image

WRITE_JPEG,'C:\Users\1046986683\Documents\Imagenes\Clase1\Fig1.07(b)Mod.jpg',image,QUALITY=100

End












